### ISSUE TITLE
"Invalid procedure" error in 1.1.19

### ISSUE THREAD

**Issue by drivehappy** [fsprojects/SQLProvider#482]
### Description

After updating from 1.1.18 to 1.1.19 I receive a compilation error within the QueryBuilder: 
```
error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Invalid procedure argument description.
```

### Repro steps

1. Use SQLProvider 1.1.19 and Npgsql 3.2.5

2. Use a QueryBuilder such as:
```
query {
  for i in ctx.Public.OmittedTable do
  where (i.Omitted = omitted)
  take 1
}
```

### Expected behavior

Compilation should succeed.

### Actual behavior

Compilation fails with:
```
error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Invalid procedure argument description.
```

### Known workarounds

Downgrade to 1.1.18.

### Related information 

* Postgres
* Windows 10
* .NET Framework 4.5.2

**Comment by piaste** [comment]
Could you post the results of these two queries, please?

```
SELECT 
             r.specific_name AS id
	          ,r.routine_schema AS schema_name
	          ,r.routine_name AS name
	          ,r.data_type AS returntype
	          ,COALESCE((
			          SELECT STRING_AGG(x.param, E'\n')
			          FROM (
				          SELECT p.parameter_mode || ';' || COALESCE(p.parameter_name, ('%s' || p.ordinal_position::TEXT)) || ';' || p.data_type AS param
				          FROM information_schema.parameters p
				          WHERE p.specific_name = r.specific_name
				          ORDER BY p.ordinal_position
				          ) x
			          ), '') AS args
          FROM information_schema.routines r
          NATURAL JOIN information_schema.routine_privileges p
          WHERE r.routine_schema NOT IN ('pg_catalog', 'information_schema')
            AND r.data_type <> 'trigger'
	          AND p.grantee = current_user
            AND p.privilege_type = 'EXECUTE'
```


```
SELECT * FROM information_schema.parameters
```

**Comment by MaybeSacred** [comment]
I'm running into likely the same issue, the root cause seems to be stored procedures/functions that have no input parameters, [like these](https://www.postgresql.org/docs/devel/static/uuid-ossp.html). Some of these produce an empty result in 'args', which fails here:

`let direction, name, typeName =`
`    match arg.Split(';') with`
`    | [| direction; name; typeName |] -> direction, name, typeName`
`    | _ -> failwith "Invalid procedure argument description."`

Running the query in the above post:

id | schema_name | name | returntype | args
------------ | -------------|-|-|-
uuid_generate_v3_16411|dbo|uuid_generate_v3|uuid|IN;namespace;uuid IN;name;text
uuid_generate_v4_16412|dbo|uuid_generate_v4|uuid|
uuid_generate_v5_16413|dbo|uuid_generate_v5|uuid|IN;namespace;uuid IN;name;text

Postgres with SQLProvider 1.1.22 if that helps

**Comment by piaste** [comment]
@MaybeSacred Thank you, the test suite was missing parameterless invocations. Will submit a PR with 
fix + regression tests soon.
