### ISSUE TITLE
Postgres type 'timestamp with time zone' causes compilation to fail with Npgsql 8.0.0 and later

### ISSUE THREAD

**Issue by mishun** [fsprojects/SQLProvider#838]
Hi!

**Describe the bug**

Basically, postgres table with `timestamp with time zone` data type, like:
```sql
begin;

create table "TestTable" (
    "ID"   int4 generated by default as identity primary key,
    "Time" timestamp with time zone
);

insert into "TestTable" ("Time") values (now());

commit;
```
causes an error on compilation, like:
```txt
/home/mishun/code/sqlprovider-bug/Program.fs(24,61): error FS3021:
Unexpected exception from provided type 'FSharp.Data.Sql.SqlDataProvider,DatabaseVendor="2",ConnectionString="Host=localhost;Port=5433;Database=test;User ID=test;Password=test",ResolutionPath="/home/mishun/code/sqlprovider-bug/obj/db-libs/",UseOptionTypes="1"+dataContext+publicSchema+public.TestTable' member 'GetMethods':
The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error:
Could not get columns for `public.TestTable`, the type `timestamp with time zone` is unknown to Npgsql type mapping [/home/mishun/code/sqlprovider-bug/sqlprovider-bug.fsproj]
```
(I've added a few line breaks for better readability)

It works correctly on `Npgsql` 7.0.9, but fails on 8.0.0 and later.

Tested with `SQLProvider` 1.4.5 from nuget package.

**To Reproduce**

Example code:
```f#
module Main

open System.Threading.Tasks
open FSharp.Data.Sql
open FSharp.Data.Sql.Common


[<Literal>]
let private resolutionPath = __SOURCE_DIRECTORY__ + "/obj/db-libs/"

[<Literal>]
let private connectionString = "Host=localhost;Port=5433;Database=test;User ID=test;Password=test"

type postgres =
    SqlDataProvider<
        DatabaseVendor   = DatabaseProviderTypes.POSTGRESQL,
        ResolutionPath   = resolutionPath,
        ConnectionString = connectionString,
        UseOptionTypes   = NullableColumnType.OPTION
    >

let test () = task {
    let ctx = postgres.GetDataContext connectionString
    let! data = Array.executeQueryAsync (query { for row in ctx.Public.TestTable do select row.Time })
    do printfn "%A" data
}

[<EntryPoint>]
let main args =
    Task.WaitAll(task {
        try
            do! test ()
        with ex ->
            printfn "Exception: %A" ex
    })
    0
```

fsproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="9.0.101" />
    <PackageReference Include="Npgsql" Version="8.0.0" />
    <PackageReference Include="SQLProvider" Version="1.4.5" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" GeneratePathProperty="true" />
  </ItemGroup>

  <Target Name="CopyDBLibs" BeforeTargets="BeforeBuild">
    <Copy SourceFiles="$(PkgMicrosoft_Extensions_Logging_Abstractions)/lib/net6.0/Microsoft.Extensions.Logging.Abstractions.dll"
          DestinationFolder="$(MSBuildThisFileDirectory)/obj/db-libs/"
          UseSymbolicLinksIfPossible="True" />
  </Target>
</Project>
```

Complete replication example with db in docker container is [here](https://github.com/mishun/SQLProvider-bug-reproduction/tree/npgsql8).
(please, note that relevant branch there is `npgsql8`, branch `master` contains example for different bug)

**Comment by Thorium** [comment]
I don't have Postgres near, but it seems to gone None here:
https://github.com/fsprojects/SQLProvider/blob/ae02e1ad25ed0d6aed324c3ad51fefeef6490fc0/src/SQLProvider.Runtime/Providers.Postgresql.fs#L761

It should fetch the types from here, and there it is: 
https://github.com/fsprojects/SQLProvider/blob/ae02e1ad25ed0d6aed324c3ad51fefeef6490fc0/src/SQLProvider.Runtime/Providers.Postgresql.fs#L186

PRs approved.

**Comment by mishun** [comment]
After poking in Npgsql souce for a bit, I think root cause here is `TimestampTZ` and `TimeTZ` being removed from `NpgsqlDbType` (in favor of `TimestampTz` and `TimeTz` correspondingly) here:
https://github.com/npgsql/npgsql/pull/5394/commits/7db9abcca60a12e2407730f6d4aee3d29b249474

after being declared obsolete here:
https://github.com/npgsql/npgsql/commit/2df716fdec3b6b55579198cda21d150e191a2e79

**Comment by Thorium** [comment]
Ok, so we could suppot both quite easily…

**Comment by Thorium** [comment]
Can you try if fix in 1.4.6 helps?

**Comment by mishun** [comment]
Wow, that was fast!

It compiles now, but throws
```txt
Exception: System.InvalidCastException: Invalid cast from 'System.DateTime' to 'System.DateTimeOffset'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at FSharp.Data.Sql.Common.SqlEntity.GetColumnOption[T](String key)
   at FSharp.Data.Sql.Runtime.QueryImplementation.executeQueryAsync@302-1.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl() in D:\a\_work\1\s\src\FSharp.Core\seqcore.fs:line 488
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System.Collections.IEnumerator.MoveNext() in D:\a\_work\1\s\src\FSharp.Core\seqcore.fs:line 530
   at Microsoft.FSharp.Collections.SeqModule.oneStepTo@1233[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i) in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 1248
   at Microsoft.FSharp.Collections.SeqModule.result@1257.Invoke(Int32 i) in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 1265
   at Microsoft.FSharp.Collections.Internal.IEnumerator.unfold@298.DoMoveNext(b& curr) in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 300
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System.Collections.IEnumerator.MoveNext() in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 113
   at FSharp.Data.Sql.AsyncOperations.executeAsync@23-1.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl() in D:\a\_work\1\s\src\FSharp.Core\seqcore.fs:line 488
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System.Collections.IEnumerator.MoveNext() in D:\a\_work\1\s\src\FSharp.Core\seqcore.fs:line 530
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source) in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 1028
   at FSharp.Data.Sql.Array.executeQueryAsync@209-21.MoveNext()
   at Main.test@22.MoveNext() in /home/mishun/code/sqlprovider-bug/Program.fs:line 24
   at Main.main@30.MoveNext() in /home/mishun/code/sqlprovider-bug/Program.fs:line 32
```
in runtime. I'd conjecture that `DateTimeOffset` here
https://github.com/fsprojects/SQLProvider/blob/c9de196209d3d6d2b25daea38f60f3479b7f7e4d/src/SQLProvider.Runtime/Providers.Postgresql.fs#L190-L192
should have remained `DateTime`.

Also, there's potential issue with `isLegacyVersion.Value` bein true for versions strictly before `3.0.0`, but `TimestampTz` and `TimeTz` were introduced in Npgsql `4.0.0`, so it probably isn't goint to work with Npgsql `3.x.x`. Are very old versions of Npgsql expected to work?

**Comment by Thorium** [comment]
Yes, it seems that the Npgsql driver maps it to DateTime. That's sad. I would really like it to be DateTimeOffset because DateTime doesn't have a time zone, and this type explicitly does. Hopefully, they'll fix it in some future version.

I'll change it back to DateTime.

For the old versions, SQLProvider tries to be backwards compatible because there are rumours that it is also used in some old enterprise systems.

**Comment by Thorium** [comment]
Fixed now as 1.4.7

**Comment by mishun** [comment]
It works now, thank you!

If I understand correctly, `timestamp with time zone` (despite its name) actually doesn't contain any time zone information and its internal representation is identical to regular `timestamp`. The only difference is how reading and writting is handled:
https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-DATETIME-INPUT-TIME-STAMPS
That kinda-sorta messed up in vaguely similar way to `DateTime` is messed up.
