### PR TITLE
Postgres CI + Fix #482

### LINKED ISSUE #482: "Invalid procedure" error in 1.1.19
### Description

After updating from 1.1.18 to 1.1.19 I receive a compilation error within the QueryBuilder: 
```
error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Invalid procedure argument description.
```

### Repro steps

1. Use SQLProvider 1.1.19 and Npgsql 3.2.5

2. Use a QueryBuilder such as:
```
query {
  for i in ctx.Public.OmittedTable do
  where (i.Omitted = omitted)
  take 1
}
```

### Expected behavior

Compilation should succeed.

### Actual behavior

Compilation fails with:
```
error FS3033: The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Invalid procedure argument description.
```

### Known workarounds

Downgrade to 1.1.18.

### Related information 

* Postgres
* Windows 10
* .NET Framework 4.5.2

### PR DESCRIPTION
**Pull request by piaste**
First, this PR contains a [pretty straightforward fix to issue #482](https://github.com/fsprojects/SQLProvider/compare/fsprojects:f1419ac...piaste:69c0b4b#diff-32c8791218a28e9d369ae420e4b0c291R468). It also contains a [fix to an undiscovered issue with array support](https://github.com/fsprojects/SQLProvider/compare/fsprojects:f1419ac...piaste:645c817#diff-32c8791218a28e9d369ae420e4b0c291R759) that only showed up when running under Mono .

Second, this PR adds compilation and testing against the Postgres provider to the CI builds. This involves the following changes:

1) Enable the Postgres service in Travis and AppVeyor
2) Add a FAKE target for non-local builds that initializes the database with the included scripts
3) Passe FAKE's `BuildServer` property to the test project as a compilation flag
4) Use the compilation flag to provide the correct compile-time connection string to the `PostgresTests.fs` file
5) Check in `System.Threading.Tasks.Extensions.dll` to enable compilation (couldn't get it to work otherwise)
6) *(in progress)* Convert the `PostgresTests.fs` file to be actual NUnit tests
7) *(TBD)* Compile the CI tests against both .NET FX and .NET Core

**IMPORTANT**: I had to comment away [a few lines from the type mapping tests](https://github.com/fsprojects/SQLProvider/compare/fsprojects:f1419ac...piaste:69c0b4b#diff-22e2f25d7fb429dad648cef1413f41b1R324) in `PostgresqlTests.fs` due to [this issue](https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/173) with the current type providers SDK, which causes compilation error when you assign a column using a CLR type from an external assembly (such as Npgsql's geometric types):

>The runtime-time type 'ctxt type NpgsqlTypes.NpgsqlBox' utilized by a type provider was not found in the compilation-time assembly set '[|FSharp.Data.SqlProvider, Version=1.1.23.0, Culture=neutral, PublicKeyToken=null;

I've left the lines commented in the PR to show that the CI works, but they should be uncommented as soon as the SDK issues are addressed. In the meanwhile, geometric types being broken should be noted as a 'Known issue' I guess?

### CODE REVIEW

**Comment by Thorium** [comment]
If Postgres build is somewhat still-in-progress, maybe we should merge fix for #482 immediately...?

**Comment by piaste** [comment]
Sure. I have another branch with just the fix, I'll make a separate PR now.

**Comment by piaste** [comment]
Sorry for leaving this PR idle, I couldn't get it to run on OSX until I stumbled on [this comment](https://github.com/travis-ci/travis-ci/issues/1875#issuecomment-263847183) explaining why the Postgres service wouldn't start 😠 

I've got the CI pipeline running now, the tests could certainly be improved further (most of them are just `Assert.IsNotEmpty`) but I think the PR could be considered for merging now. Adding a second .NET Core pipeline can come later.

Note that the issue with the Npgsql-specific types seems still present even after rebasing on the current master (1.1.29), despite the recent SDK updates.

**Comment by Thorium** [comment]
Thanks!
However, now the build is failing for that: https://travis-ci.org/fsprojects/SQLProvider/jobs/335392877

**Comment by piaste** [comment]
Hmm. Seems to fail when the postgres service sometimes takes too long to start and the last `createuser` command runs too early. I've added a loop to wait for the database to start and sent a PR: https://github.com/fsprojects/SQLProvider/pull/513
